Weather/Models/Clouds.cs
namespace Weather.Models
{
    public class Clouds
    {
        public int all { get; set; }
    }
}

Weather/Models/Coord.cs
namespace Weather.Models
{
    public class Coord //координаты
    {
        public double lon { get; set; }
        public double lat { get; set; }
    }
}

Weather/Models/Main.cs
namespace Weather.Models
{
    public class Main
    {
        public double temp { get; set; }
        public int pressure { get; set; }
        public int humidity { get; set; }
        public double temp_min { get; set; }
        public double temp_max { get; set; }
    }
}

Weather/Models/ResponseWeather.cs
using System.Collections.Generic;

namespace Weather.Models
{
    public class ResponseWeather
    {
        public Coord coord { get; set; }
        public List<Weather> weather { get; set; }
        public string @base { get; set; }
        public Main main { get; set; }
        public int visibility { get; set; }
        public Wind wind { get; set; }
        public Clouds clouds { get; set; }
        public int dt { get; set; }
        public Sys sys { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public int cod { get; set; }
    }
}

Weather/Models/Sys.cs
namespace Weather.Models
{
    public class Sys
    {
        public int type { get; set; }
        public int id { get; set; }
        public double message { get; set; }
        public string country { get; set; }
        public int sunrise { get; set; }
        public int sunset { get; set; }
    }
}

Weather/Models/Weather.cs
namespace Weather.Models
{
    public class Weather 
    {
        public int id { get; set; }
        public string main { get; set; }
        public string description { get; set; }
        public string icon { get; set; }
    }
}

Weather/Models/Wind.cs
namespace Weather.Models
{
    public class Wind
    {
        public double speed { get; set; }
        public double deg { get; set; }
    }
}

Weather/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Weather.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Weather/Controllers/OpenWeatherMapMvcController.cs
using Newtonsoft.Json;
using System;
using System.IO;
using System.Net;
using System.Web.Mvc;
using Weather.Models;

namespace Weather.Controllers
{
    public class OpenWeatherMapMvcController : Controller
    {
        private static string ApiKey = "f53b600213f56cf6284a15e540b85796"; //ключ для доступа к OpenWeatherMap
        // GET: OpenWeatherMapMvc
        [HttpGet]
        public ActionResult Index()
        {
            ResponseWeather responseWeather = GetWeatherByCiti("Kyiv"); // Информция о погоде в Киеве отображается по умолчанию.
                                                                        //можно было бы использовать определение города по IP юзера но это коректно работает только с развернутым сайтом а не при использовании локального сервер
            return View("~/Views/OpenWeatherMapMvc/Search.cshtml",responseWeather); //вызов представления и передача модели
            
        }

        [HttpPost]
        public ActionResult Index(string cities)
        {
            ResponseWeather rootObject = null;
            if (!string.IsNullOrEmpty(cities)) //проверяем есть ли символы в строке
            {
                rootObject = GetWeatherByCiti(cities);//ищем погоду по названию города
                if (rootObject != null)//проверяем получили ли мы данные о погоде в указанном нами городе
                {
                     return View("~/Views/OpenWeatherMapMvc/Search.cshtml", rootObject);//вызов представления и передача модели
                }
            }
                return Content("You did not specify a city or the specified city was not found!");//Error
            
        }

        private static ResponseWeather GetWeatherByCiti(string cities)
        {
            ResponseWeather rootObject;
            HttpWebRequest apiRequest = WebRequest.Create("https://api.openweathermap.org/data/2.5/weather?q="
                                        + cities + "&appid=" + ApiKey + "&units=metric") as HttpWebRequest;//запрос по названию города

            string apiResponse = "";
            try
            {
                using (HttpWebResponse response = apiRequest.GetResponse() as HttpWebResponse)//используем using для подключению в к вyешнему Api
                {
                    StreamReader reader = new StreamReader(response.GetResponseStream());//создаём поток для чтения данных
                    apiResponse = reader.ReadToEnd();//считываем данные и получаем JSON
                }
            }
            catch (Exception)
            {
                return null;
            }
           
            rootObject = JsonConvert.DeserializeObject<ResponseWeather>(apiResponse);//преобразовываем получиный JSON в модель ResponseWeather
            return rootObject;
        }
    }
}

Weather/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Weather/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Weather/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Weather/Views/OpenWeatherMapMvc/Search.cshtml
<h1>Search</h1>

@using (@Html.BeginForm("Index", "OpenWeatherMapMvc",FormMethod.Post))
{
    <div class="row">
        <div class="col-md-2 myClass">
            <h4>Enter citi name:</h4>
        </div>
        <div class="col-md-8">
            <input type="text" name="cities" class="form-control" />
        </div>
        <div class="col-md-2">
            <input class="btn btn-success btn-block" type="submit" value="Search" />
        </div>
    </div>
}
@Html.Partial("~/Views/OpenWeatherMapMvc/Weather.cshtml")

Weather/Views/OpenWeatherMapMvc/Weather.cshtml
@model Weather.Models.ResponseWeather

<table class="col-md-4 table table-striped table-hover table-bordered">
    <tr>
        <th>Weather Description</th>
    </tr>
    <tr>
        <td>Citi: @(Model.name ?? string.Empty)</td>
    </tr>
    <tr>
        <td>Country: @(Model.sys.country ?? string.Empty)</td>
    </tr>
    <tr>
        <td>Wind: @(Model.wind.speed.ToString() ?? string.Empty) Km</td>
    </tr>
    <tr>
        <td>Current Temperature: @(Model.main.temp.ToString()  ?? string.Empty) °C</td>
    </tr>
    <tr>
        <td>Humidity: @(Model.main.humidity.ToString()  ?? string.Empty)</td>
    </tr>
    <tr>
        <td>Weather: @(Model.weather[0].description  ?? string.Empty)</td>
    </tr>

</table>

Weather/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("Информация", "About", "Home")</li>
                    <li>@Html.ActionLink("Связаться", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Wheter", "Index", "OpenWeatherMapMvc")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>